### PR TITLE
Solr v3 compatibility 

### PR DESCRIPTION
**Pull request by MrPingoo**
Update Solr path and class name for EXT SOLR v3.0.0 .

### CODE REVIEW

**Comment by dkd-dobberkau** [comment]
I would love to accept this if you did not change the authors in the ext_emconf.php. Can you revert the changes there and resubmit. feel free to add a changes.md to add your authorship.

**Comment by jacobsenj** [comment]
I think the problem is, the ext_emconf.php was not there in the first place

**Comment by MrPingoo** [comment]
Please add the ext_emconf.php file in your own repository and I add it on fork.

**Comment by dkd-dobberkau** [comment]
OK. Will take care of this.

**Comment by dkd-dobberkau** [comment]
I will accept the PM and change the emconf then.

**Pull request merged**
